from apps.HttpTestcas.views.envs import *
from apps.HttpTestcas.views.interfaces import *
from apps.HttpTestcas.views.module import *
from apps.HttpTestcas.views.project import *
from apps.HttpTestcas.views.reports_details import *
from apps.HttpTestcas.views.testcase_reports import *
from apps.HttpTestcas.views.testcases import *
from apps.HttpTestcas.views.testsuite import *
from apps.HttpTestcas.views.user import *
from apps.HttpTestcas.views.testsuite2testcase import *
from apps.HttpTestcas.views.testsuite_reports import *
