# Generated by Django 3.1.2 on 2021-04-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('module', '0001_initial'),
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='接口名称', max_length=200, unique=True, verbose_name='接口名称')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('url', models.TextField(verbose_name='接口请求URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], default='GET', max_length=11, verbose_name='接口请求方法')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='接口请求头信息')),
                ('request_data_type', models.CharField(choices=[('Json', 'Json'), ('Form Data', 'Form Data')], default='Json', max_length=11, verbose_name='接口请求参数类型')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='接口请求体参数')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('desc', models.CharField(blank=True, default='', help_text='描述信息', max_length=200, null=True, verbose_name='描述信息')),
                ('envs', models.ForeignKey(help_text='运行环境', on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='envs.envs')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='module.module', verbose_name='所属模块')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.projects')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'tb_interfaces',
            },
        ),
    ]
