# Generated by Django 3.1.2 on 2021-04-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('name', models.CharField(help_text='用例名称', max_length=200, unique=True, verbose_name='用例名称')),
                ('url', models.TextField(blank=True, null=True, verbose_name='接口请求URL')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='接口请求头')),
                ('request_data_type', models.CharField(choices=[('Json', 'Json'), ('Form Data', 'Form Data')], default='Json', max_length=11, verbose_name='接口请求参数类型')),
                ('request_params', models.TextField(blank=True, null=True, verbose_name='接口查询参数')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='接口请求参数')),
                ('expect_result', models.TextField(blank=True, null=True, verbose_name='期望结果')),
                ('level', models.CharField(choices=[('LOW', '低'), ('NORMAL', '中'), ('HIGH', '高'), ('HIGHER', '更高')], default='NORMAL', max_length=12, verbose_name='用例级别')),
                ('status', models.CharField(choices=[('INITIAL', '初始状态'), ('PASS', '通过'), ('FAIL', '失败')], default='INITIAL', max_length=11, verbose_name='是否测试通过')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcase', to='interfaces.interfaces', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'db_testcases',
            },
        ),
    ]
