# Generated by Django 3.1.2 on 2021-04-23 10:25

from django.db import migrations, models
import django.db.models.deletion
import testcase_reports.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE')], default='GET', max_length=11, verbose_name='接口请求方法')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='接口请求头信息')),
                ('request_data_type', models.CharField(choices=[('Params', 'Params'), ('Json', 'Json'), ('Form Data', 'Form Data')], default='Json', max_length=11, verbose_name='接口请求参数类型')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='接口请求参数')),
                ('actual_status_code', models.CharField(max_length=11, verbose_name='实际响应状态码')),
                ('actual_response_data', models.TextField(verbose_name='实际响应结果')),
                ('execute_time', models.DateTimeField(verbose_name='执行时间')),
                ('elapsed_ms', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='响应时长(ms)')),
                ('status', models.CharField(choices=[('PASS', '通过'), ('FAIL', '失败')], default='FAIL', max_length=11, verbose_name='是否测试通过')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='测试未通过原因')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('api_name', models.CharField(max_length=128, verbose_name='接口名称')),
                ('testcase_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('is_periodictask', models.BooleanField(default=True, verbose_name='是否是定时任务')),
                ('version', models.CharField(default=testcase_reports.utils.get_version, max_length=13, verbose_name='版本号')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interfaces.interfaces', verbose_name='所属接口')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projects', verbose_name='所属项目')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcase_result', to='testcases.testcases', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例测试报告',
                'verbose_name_plural': '用例测试报告',
                'db_table': 'db_testcase_reports',
            },
        ),
    ]
